Account for MPEGTS rollover when adjusting vtt cues
videojs/http-streaming pull request #1334
Opened 2022-10-13 21:20 UTC by raytiley

## Description
This fixes an issue with a long running stream where the cue start times are larger than the maximum mpegts timestamp of ~27 hours.

## Specific Changes proposed
VTT cue start and end times are adjusted to ensure that they are within the range of mpeg ts PTS which has a max size of 2^33.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

2022-10-14 23:18 UTC, gkatsev commented on src/vtt-segment-loader.js
> +    const mpegTsRollover = Math.floor((2**33) / ONE_SECOND_IN_TS);
nit: to fix linter errors
```suggestion
    const mpegTsRollover = Math.floor((2 ** 33) / ONE_SECOND_IN_TS);
    
```

2022-10-14 23:18 UTC, gkatsev commented on src/vtt-segment-loader.js
> +    const mpegTsRollover = Math.floor((2**33) / ONE_SECOND_IN_TS);
I wonder if there's a way to know whether TS segments are used here and only apply this rollover in those cases. @gesinger thoughts?

2022-10-25 13:59 UTC, raytiley commented
@gkatsev / @gesinger - Any thoughts on what I can do to get this in? Thanks!

2023-02-23 19:12 UTC, misteroneill reviewed
@raytiley Sorry for the delay on this. I've changed the base branch to 2.x - can you verify that the diff looks correct to you?

2023-04-04 17:59 UTC, adrums86 requested changes
It would be great to see a test for this.

2023-04-04 18:18 UTC, adrums86 commented on src/vtt-segment-loader.js
> +    const mpegTsRollover = Math.floor((2 ** 33) / ONE_SECOND_IN_TS);
Since this code isn't isolated to TS segments, we may want to use the actual media timescale rather than `ONE_SECOND_IN_TS` (90000).

2024-01-11 00:43 UTC, dzianis-dashkevich commented
I assume that this PR should handle this case as well:
https://github.com/videojs/http-streaming/pull/1472

PS: it is not related to TS segments only. There might be cases when we have CMAF for video/audio, and VTT might still have an MPEGTS timestamp map.

2024-04-12 03:54 UTC, adrums86 commented
I think this was handled in this PR https://github.com/videojs/http-streaming/pull/1472. @raytiley please let me know if this doesn't fix your rollover issue. Closing for now.

2024-04-12 03:54 UTC, closed without merging