fix(docs): Remove confusion around including VHS separately
videojs/http-streaming pull request #1367
Opened 2023-02-03 09:29 UTC by mister-ben

The doc example was confusing, leading some people to including a VHS separately. Makes it clearer that including the VHS script shouldn't be necessary, and when so to use the core video.js.

## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

2023-02-03 15:06 UTC, phloxic commented on README.md
> +Only install if you need a specifc compination of video.js and http-streaming versions. If installing separately, use the "core" version of Video.js without the bundled version of http-streaming.
s/compination/combination/ ;-)

2023-02-23 19:30 UTC, misteroneill requested changes

2023-02-23 19:30 UTC, misteroneill commented on README.md
> +These browsers have some level of native HLS support, however by default the [overrideNative](#overridenative) option is set `true` except on Safari, so MSE playback is used:
```suggestion
These browsers have some level of native HLS support, however by default the [overrideNative](#overridenative) option is set to `true` except on Safari, so MSE playback is used:
```

2023-02-23 19:30 UTC, misteroneill commented on README.md
> +This library is included in video.js 7 by default.
```suggestion
This library is included in Video.js 7 by default.
```

2023-03-14 18:12 UTC, gkatsev approved these changes

2023-04-04 15:23 UTC, misteroneill approved these changes

2023-04-04 15:37 UTC, merged